version: '3'
services:
  influx_db:
    image: influxdb:2.0
    container_name: garden_influx
    ports:
      - '8086:8086'
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb2
    restart: unless-stopped

  grafana:
    image: grafana/grafana:7.3.7
    container_name: garden_grafana
    ports:
      - 3000:3000
    user: '472'
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    restart: unless-stopped

  task_runner:
    build: ./PyTasks
    container_name: garden_pytasks
    restart: unless-stopped
    command: python3 -u main.py
