version: '3'
services:
  influx_db:
    image: influxdb:2.0
    container_name: garden_influx
    ports:
      - '8086:8086'
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb2
    restart: unless-stopped
