version: '3'
services:
  influx_db:
    image: influxdb:2.0
    ports:
      - '8086:8086'
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password

  grafana:
    image: grafana/grafana:7.3.7
    ports:
      - 3000:3000
    volumes:
      - ./volumes/grafana:/var/lib/grafana
